# Colors (One Half Dark)
[colors.bright]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xdcdfe4"
yellow = "0xe5c07b"

[colors.normal]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xdcdfe4"
yellow = "0xe5c07b"

[colors.primary]
# background = "0x282c34" # (one half dark)
background = "0x300924" # (Ubuntu)
foreground = "0xdcdfe4"

[env]
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
# family = "HackNerdFont"
# family = 'Monaspace Neon'
# family = 'Monaspace Argon'
# family = 'Moralerspace Neon'
family = 'Moralerspace Xenon'
# family = 'Bizin Gothic'
style = "Bold"

[font.italic]
# family = "HackNerdFont"
# family = 'Monaspace Neon'
# family = 'Monaspace Argon'
# family = 'Moralerspace Neon'
family = 'Moralerspace Radon'
style = "Italic"

[font.normal]
# family = 'Mononoki NerdFont'
# family = 'Monaspace Neon'
# family = 'Monaspace Argon'
# family = 'HackNerdFont'
# family = 'Moralerspace Neon'
family = 'Moralerspace Argon'
# family = 'Moralerspace Xenon'
# family = 'Bizin Gothic'
style = "Regular"

[window]
opacity = 0.9
